image:
  repository: ghcr.io/cloudraftio/metrics-app
  tag: "1.4"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

# env:
#   PASSWORD: "MYPASSWORD"

env:
- name: PASSWORD
  valueFrom:
    secretKeyRef:
      name: app-secret
      key: PASSWORD

ingress:
  enabled: false  

autoscaling:
  enabled: false  

serviceAccount:
  create: true
  annotations: {}
  automount: true

