image:
  repository: ghcr.io/cloudraftio/metrics-app
  tag: "1.4"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080

# env:
#   PASSWORD: "MYPASSWORD"

env:
- name: PASSWORD
  valueFrom:
    secretKeyRef:
      name: app-secret
      key: PASSWORD

serviceAccount:
  create: true
  annotations: {}
  automount: true

ingress:
  enabled: false  # or true, depending on whether you want ingress

autoscaling:
  enabled: false  # or true, depending on what you need
